[package]
name = "ty"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
once_cell = "1.21.3"
phf = "0.13.1"
reqwest = "0.12.24"
tokio = { version = "1.48.0", features = ["full"] }
